In [14]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr)

arr = np.arange(10)

print(arr)

arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

print(arr)

print(arr.ndim)

print(arr.shape)

print(len(arr))



[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
2


In [15]:
arr = np.arange(1,11,2)

arr

array([1, 3, 5, 7, 9])

In [16]:
arr = np.linspace(1,10,6)

arr

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
arr = np.diag([1,2,3])

arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
np.diag(arr)

array([1, 2, 3])

In [20]:
np.random.randn(10)

array([ 0.3796191 ,  0.29222258,  0.19261908, -0.70057439, -0.24443867,
        0.58171594, -0.83518813, -0.76393673, -1.22442995, -0.97404775])

In [21]:
data = np.loadtxt('populations.txt')

data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [22]:
years, hares, lynx, carrots = data.T


In [23]:
#find mean population of hares

np.mean(hares)

34080.95238095238

In [44]:
#who had the highest population each year

labels = ['', 'hares', 'lynx', 'carrots']


lst = np.argmax(data[1:],axis=1)


for ind in lst:
    print(labels[ind])



carrots
hares
hares
lynx
lynx
carrots
carrots
carrots
carrots
carrots
carrots
hares
hares
hares
lynx
carrots
carrots
carrots
carrots
carrots


# Broadcast

In [30]:
# Repeat the array formed from np.arage for 3 rows and 2 column

arr = np.tile(np.arange(0,40,10),(3,2))

print(arr)

arr = arr.T

print('*********')

print(arr)

small_arr = np.array([1,2,3])

arr + small_arr

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]
*********
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]
 [ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

## New Axis

In [37]:
arr = np.arange(0,40,10)

print(arr)

print('------')

arr = arr[:,np.newaxis] #converts 1D array to 2D array

print(arr)

print('-----')

b = np.array([1])

arr + small_arr

[ 0 10 20 30]
------
[[ 0]
 [10]
 [20]
 [30]]
-----


array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

# Flattening and Reshaping

In [40]:
arr = np.arange(4*3*2).reshape(4,3,2) #Reshape an array into mentioned dimensions

print(arr)

np.ravel(arr) #Flatten a multi-dimensional array to 1D array

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# Sort and Argsort 

In [59]:
arr = np.array([[60,4,1],[1,45,0]])

print(arr)

print('Row-wise sorting')

arr.sort(axis=1) #row-wise sorting

print(arr)

arr = np.array([[60,4,1],[1,45,0]])

print('Column-wise sorting')

arr= np.sort(arr,axis=0) #col-wise sorting

print(arr)

arr = np.array([[60,4,1],[1,45,0]])

print('Return index of row-wise sorted array')
ind = np.argsort(arr,axis=1) 

print(ind)

[[60  4  1]
 [ 1 45  0]]
Row-wise sorting
[[ 1  4 60]
 [ 0  1 45]]
Column-wise sorting
[[ 1  4  0]
 [60 45  1]]
Return index of row-wise sorted array
[[2 1 0]
 [2 0 1]]
